//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonLib.Web.Identity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExtendedIdentityDbEntities : DbContext
    {
        public ExtendedIdentityDbEntities()
            : base("name=ExtendedIdentityDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TUserSession> TUserSessions { get; set; }
        public virtual DbSet<TAccessRight> TAccessRights { get; set; }
        public virtual DbSet<TRoleAccess> TRoleAccesses { get; set; }
        public virtual DbSet<TAuthClient> TAuthClients { get; set; }
    }
}
