//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonLib.Web.Identity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRoleAccess
    {
        public System.Guid AccessId { get; set; }
        public long RoleId { get; set; }
        public bool IsActive { get; set; }
    }
}
